dnsRecords:
- domain: 192.168.0.0
  address: "example.home.lab"

replicaCount: 2

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

image:
  repository: cytopia/bind
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: "dns"
fullnameOverride: "dns"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  loadBalancerIP: ""
  annotations:
    metallb.universe.tf/address-pool: mainpool
    metallb.universe.tf/allow-shared-ip: "dnskey"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
