---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: traefik
spec:
  encryptedData:
    api-token: AgAbvpu8Zd326H9Gpl0NmCBvvoiBalAh8lc7xhHbzLD3gMhSyoW4kxr+qoC6z7ZvdensDZmGaiO+g0C1HbR/jNkqbL9ntSBAdcRAUsAfSL68wcJURA6lETDKkI2reG2zgLT4YkTwSLf8XDmCNXfbStJZY4MPlTW+Z3W/ultCUlG5kgz+tB4+kWV31STc5ACXdjTe7Z4/8sLTnAuIeMxrHWhFz/C2+zdF3HmG0ZOLCbZKnepeJmEvU9EDtYDYzdB80pzZuhxkZ6QzqFHKrY5oljefIx0ptE5GXntaVgpUAxUUufzGNPcjKO3BsqecwRw8I8DzWlQ5YfS8X02rr8MOGu0YuEby8qAxNWYNpr/zUSJnxm/zzDWPieyCb8IFKweeWS17eyGb4WOlVMraCxIk7VGaftnFF8d5WZdzqotm81AJ21o4WAvFRwviRJ3Wb8zg34bsW8GxaLKI7vUENpVVohcho68VTO0dMDBPmg6wv46vpYWlX/oh9quIySn9w5LW1oj97v4Cb4/fIFssJ4LFxXrdHAKcSc/AGE++TdWgzrIAoX5fwbu74xRyC+o5qwroaYjMDfkPLt5u/EzLGvmPGtK+76sSa/+660w4GhGDQ0IaW76eLpue0vt6yQFkdRTd+aDCBr7Csr4tKVR91ZdvZGB0aTHsdRedoVZR/tOdDTKkzbcP/gvCLZPbIyT5HYcdavoGlldIxdQW/7K+baM6zo06x0K1vWFxQLgNHY2C+uk0dxYjw8WjQaXw
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: traefik
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgC5Cgyj56+zraPb0Y1+yQ7Q4rm58hOi/QfprP1MuOWaSSejwlnF+y2xnHgc+wHYPf1ujMSKRm9oKkxVDONylno8Pq1kgbYRDyncnB82GFXcs+DEjjnLgv/4n3fv3FOexqJBmGrlP3kSFf2wSqMfQRRqxKUw74rFcRPw8YZ+9YnwLbRvpgCg0Ge1FjPsgLx8+vsWCMcegww7LxT9yyDvc1y05+gz+/X2Yd8n5MYG1LEF6SVr83/au3HacPwY6RseH/0tcEJcvV3k72tAUft9tzg524ho3Jl+D1b77c6DF1/3+d/ICmpDEGaGHZKT5Piar6LQ3Xtz+PHVUsRUuEuzIbiLkaggJaTn3qBAl+Bki/pZM3n3TRaHW3vwAok5Ux3Mr7sk3HjGC6UBi9hKc33+BHPl8gIotOrMcuYB6AYU/rd0v46rIvc8O61yrFcMtSPIkIWou2IzWF7rJkB7PAQA1+OOwHUIKA0SbGT5Sro964Cqh4bcrojXf/gaQOXghcRL4RJrMhM6aATS1UcM+rm9vuYUFlDhkrF/KqZFDaPPwRo05J7/UEbY67+tAz58edf3XbbO24YqazBXKalcxnaw5u/B4fjIDLcfyVO+8F1J0jUoqmykgjBDP4irQsrqeiE9nFbhlJ2J94wZ/eYPfzjhpx6DAYGXbbxTq5Z9mKz2CkW0RJBpvCAqhmQ5QL9Ty6/iZICbxo5m11nYHacm0E46/cQcfcL+m5Cf83jOvGQetU80MzmUJ30uXzrv
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: cert-manager
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgAH3NfUf7zGqE2MEzVHBEeFcg1kTfYuHlF1FavoaPSyuVsYIxVMJwXHNsd4U5dtPql9HyOPXS79d3LHo5HQkR2Y1DkapJNhatmjs2dPgpKFyjpkcAdB2WpudSSYJzi/Hl1BHqsVBaup+URoW701exOHYQBEUpVzj0s1PxGsApjtwaG81lszo9SF10Gu6FYRyv6Z8HECxDPaqRpPh0Zd+UX9BgG3Ok40fIXlEq1cT6a7mXUFJe0p1R6Fd8HL1NiKxSkDVJh66Xuir2M3C9Hb9gJzYtAdGs+k0rcjUDGZu20rmBsvBYw9FGUS203vcLHegcl7VhJKKgyo+EJNPemuVkvmZPK8XBcLw32dVinPX0IdiHSEGNi7qvR2llF6s8sH0tg/1K2LreBmpzNRCVc5CrKaIiGIGfm87hrbWUpqgl4h4sDSuAXpKWKuFW84h27t9QLe48bwrz7g8tTLDFH0nZ25abBU1xmcnMUvYUtASvvdkkTgRpbwqXWsN1sAW7tvBjSONhEmA5y/NbyHiSLr1qOBBfJ/J1iVfnftoA9jYdWF1kfYCXxRSvh0Mx5l9jzOjiPxzYACHhMys8z0/9XNJ31z7nHp8uy2F6xZnGutgh9FxGtgFineHMPJNi3FCy7nq6myBW1VyuKGwRCwPHiyNhnYQT4Kb4FKayw503wlP+h7Z5ftY5kZH5CkWmk/qnsBZbVKxK52lLG9DU9/iE9IheG13Mopz3uBvbvXB4E6hSv1kpKRaeykHY0i
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: external-dns
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: onkyo
spec:
  encryptedData:
    api-token: AgDJYIHXIsyJPQuQOpNrSDIUdVMyxjwoh/ln1U8tGAeQ8k6Ns/BcQPD7L2Xu/g9VF6CgZFK+2SfggMjrSpIn1tEbTTAEBH88DqLq7vGrGH44lUNSTTGsaVPrSF93PDMxYazzBogwTHbaImufdOVC2i5zGJy6JhnvP7bBkEUXzpNCZ6QMwm/DnMo4Yp8NgvcJPCsPmC28YMkYyUV24LvS/e22ENRdFSHTkthvqwcqvGRsMTHLDJJpC5lRqthe2sCut9odWRBgb5WgJ2EtQ6t+7KSQ3haEegbLbdGIEtGM3vCegnKLlXUv3EXEpDPX3YCaFIeqmK7A7PFDDiPpdZnXSNruXQ+EaFmleNPnBNFKtFe16OBB4ZpR5lVLy0LYL2YG7O3k0+Nf8C/nelCdpI17PqGSCH+GnChnXgMrb9p8kRfmldjTAJjk5uV+zqV0n+j+iDcgjmlfmvBbZP/YA9qi79D+HHXSZWcUXGE33bVdo9g4NdYlYadLyNUCE6xZ+Qi0XeZ8MSLnm024tMtEYBbHIH2Q0sg5Wsk4b3wm3yUbjohHlag8NjFMlKGnuF66y5MHZ9hLwIDmehvDhiTgSmMdF1gUGrNX4F1M2M11FB23MMLscSa+h7VUCBxkHU6WO/lXysPXJizP2BLDEDA55TuR5X39FzSLxTKzhCDK5dOrAap/uKqfh9IIi74cllLlachDE5qo5iWcaeReMtu0ATVRB+MWPripEYyQwhDynFxzeisGDGtdwjxxh2Dl
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: onkyo
    type: Opaque
