---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBFUsWXLUTazmRcz9/XkcWC68WXswPtkt55iwr2ngCu8QvKGgPjEegoWNaIPUiD2/RxX0cb0JH0BY3lEWux9tz2jGKNc6TYBWRygXgHMniNN3ceTbIGHpDjWvfio5pb0y7Z+/6QvCY590xlV2AuQh8Yv5nJnmLYrNsvG1iJ1qv77jD4GyteGwnff1PH5YNk7orsHyrtNFKWO6WmbN+Bn6GkDF8PEkeUYqB83/dqK8M3ggbcX6mK5TZRDwGT/LTBSAhZRpfuf/s6cIxnxHEG+X/P6HUjv3Oq0wxpApNy+jFs3tTSvm9R4SkjL35Mcc1KBKoVZnk3Cr/kMyfalzNj8Xl4MZUR+HTpw7JNgz4M0yxufFWGVj1/Rz8iDJq9esv6KWR68uo74ZNRxvYH4WDxWDNPxexjiiUPyrwO8FuEvh7FXqdlqw+yRnDWheFrHkeYJ+dKdIOHGhovaJF4YqLAV5mBWxPNdIG6CbqHFg04p98A7fhUWxQtCyw+EDbFBUJ/CeIg0QyQt2GA00YSJliEus9l2PTkPdYM8uRlhqAsPtr8w9UsKpFgl9F4LanN8J8nKK/Sh4NLpkrufOUD37V8lhuIt/LJJKCeTSkkNf68+Cn5Re5aNjQcweyUMAfsCAJe2TjK9HgLUDxc5AAmvhKuJw1hA6QfnuOB6hfPC0Ea1mzMq/u/xf9n65u2LM4+odDK+rAe1M54U4NoLbvCdsZwU2yajw==
    client_secret: AgBpOysPzyhJVlRTTXK6YLrpVI1ZDyUi+OIy6FcwyAzAt9k+jfcFQXnFyP6kpm1qycgoSDfBK3RBX+dAn8Lfu8ZRDHQ+Zdb71u24FE7AuJ1OIw1tAaVZ1RsOFwI4jS7RBVCYEVdciGpL5Mldtkn2MTx35xMVkUvCFtcFm6soluBvBrdRd3Po+GJOZqxBmxNxEnR9WnJ+bB6kv75ZkzHnViHJKeO+u5GmSIhV1xwQSyj0bFoXNIRRhldh+8jM6sTutuHsviFSUXZSrWwYlr4LQVfx32MPG+eKCDfys2iMawS7/GIvMoJDi7Gsu89WY7/k1eKEbgweraf6uqAdNDvZwxumJ3PJHnPWKvOKesxfPzo3FaGwibTWHdDfn77floFM7LNAohTNSkrPRN95kMrNb/Xuce21dzvvrBW7FSYvWAXy/kfHkdP0aWUCMIvrv36a6T4XTospKuFfV0BXYV8Ue7mQjnl3eNstrW/Mh+yXrL201dXzf0NLTawXGoa95/i+I9ZxzCEWHkT9imbcVQxfIgBNfEADS+1m+uprUvQwUIuvymeK3tspu279QFCqA/wqXqd+uAXbmeeMUy39zsc5TaVAbitfiqArKR5OHtXVbgsP0vHpGzWBJ8PDWzy8TJ//AstO37qJJS3p3Lm0Rbo9NMhXTg8uumBY4dgUB3amq8O3N36wxGKYuBu6TtXjq90JQyMUmI7312pmrTjtdMiaBjPBNfcApgGkSY/DFqhg5tp+GWOTqS3u4Ldi0gOE9clwwbBaV3b+16bCm29sTIyPmI8=
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
    type: Opaque
