apiVersion: v1
kind: Namespace
metadata:
  name: custom-dns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns
  namespace: custom-dns
spec:
  selector:
    matchLabels:
      app: dns
  replicas: 2
  template:
    metadata:
      labels:
        app: dns
    spec:
      containers:
      - name: dns
        image: cytopia/bind
        ports:
        - containerPort: 53
        env:
        - name: DNS_A
          value: example.home.lab=192.168.0.241
        - name: ALLOW_QUERY
          value: any
        - name: DOCKER_LOGS
          value: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: dns-service-udp
  namespace: custom-dns
  annotations:
    metallb.universe.tf/address-pool: mainpool
    metallb.universe.tf/allow-shared-ip: "dnskey"
spec:
  selector:
    app: dns
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
  type: LoadBalancer
  loadBalancerIP: 192.168.0.240
---
apiVersion: v1
kind: Service
metadata:
  name: dns-service-tcp
  namespace: custom-dns
  annotations:
    metallb.universe.tf/address-pool: mainpool
    metallb.universe.tf/allow-shared-ip: "dnskey"
spec:
  selector:
    app: dns
  ports:
    - protocol: TCP
      port: 53
      targetPort: 53
  type: LoadBalancer
  loadBalancerIP: 192.168.0.240
