apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onkyo
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/edfincham/homelab.git
    path: helm/charts/onkyo
    targetRevision: HEAD
    helm:
      releaseName: onkyo
      valuesObject:
        image:
          repository: edfincham/onkyo-rpi
          pullPolicy: IfNotPresent
          tag: "latest"
        nameOverride: "onkyo"
        fullnameOverride: "onkyo"
        securityContext:
          privileged: true
        service:
          enabled: true
          port: 80
          targetPort: 8080
          type: ClusterIP
        ingress:
          enabled: true
          className: "traefik"
          annotations:
            traefik.ingress.kubernetes.io/router.tls: "true"
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            cert-manager.io/cluster-issuer: cloudflare
          hosts:
            - host: onkyo.homeiswherethelabis.org
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - onkyo.homeiswherethelabis.org
              secretName: onkyo-server-tls


        tolerations:
        - key: device
          operator: Equal
          value: hifi
          effect: NoSchedule
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: device
                  operator: In
                  values:
                  - hifi
  destination:
    server: "https://kubernetes.default.svc"
    namespace: onkyo
