apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: owlet
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/edfincham/owlet-sock-scraper.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: owlet
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
