apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spotify-connect
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/edfincham/rpi-spotifyd.git
    path: k3s
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: spotify-connect
