apiVersion: v1
kind: Service
metadata:
  name: {{ include "onkyo.fullname" . }}
  namespace: {{ include "onkyo.fullname" . }}
  labels:
    {{- include "onkyo.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  selector:
    {{- include "onkyo.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
