apiVersion: v1
kind: Service
metadata:
  name: {{ include "dns.fullname" . }}-udp
  namespace: {{ include "dns.fullname" . }}
  labels:
    {{- include "dns.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  selector:
    {{- include "dns.selectorLabels" . | nindent 4 }}
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
  type: {{ .Values.service.type }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dns.fullname" . }}-tcp
  namespace: {{ include "dns.fullname" . }}
  labels:
    {{- include "dns.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  selector:
    {{- include "dns.selectorLabels" . | nindent 4 }}
  ports:
    - port: 53
      targetPort: 53
      protocol: TCP
  type: {{ .Values.service.type }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
